version: "3.9"  # optional since v1.27.0
services:
  gfuse:
    privileged: true
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./docker.env
    volumes:
      - $GOOGLE_APPLICATION_CREDENTIALS:/tmp/keys/sa-instance.key.json:ro
    devices:
      - /dev/fuse
